# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-14 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='billing',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
