# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-15 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0003_auto_20190815_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_form', to='login.User'),
        ),
    ]
