# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-26 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='User',
        ),
    ]
