# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-07 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
