# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-08 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
